import type { Metadata } from "next";
import "./globals.css";
import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";
import { ReactNode } from "react";
import GravityProvider from "@/app/GravityProvider";
import StoreProvider from "@/features/StoreProvider";

export const metadata: Metadata = {
  title: "TODO CRUD",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
  create: ReactNode
}

export default function RootLayout({ children, create }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <GravityProvider>
            {children}
            {create}
          </GravityProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
